### ISSUE TITLE
No such file or directory: 'I830000_E32_gen.pth'

### ISSUE THREAD

**Issue by iitjee** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#30]
I tried upscaling a simple picture using the colab notebook but instead getting this "No such file.." error on running the last cell
![download](https://user-images.githubusercontent.com/20602254/141614733-99adf087-ce2f-4f1f-8e7b-c208f026119b.jpg)

21-11-13 09:59:49.904 - INFO: Dataset [LRHRDataset - CelebaHQ] is created.
21-11-13 09:59:49.904 - INFO: Initial Dataset Finished
21-11-13 10:00:06.355 - INFO: Loading pretrained model for G [I830000_E32] ...
Traceback (most recent call last):
  File "infer.py", line 46, in <module>
    diffusion = Model.create_model(opt)
  File "/content/Image-Super-Resolution-via-Iterative-Refinement/model/__init__.py", line 7, in create_model
    m = M(opt)
  File "/content/Image-Super-Resolution-via-Iterative-Refinement/model/model.py", line 42, in __init__
    self.load_network()
  File "/content/Image-Super-Resolution-via-Iterative-Refinement/model/model.py", line 158, in load_network
    gen_path), strict=(not self.opt['model']['finetune_norm']))
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'I830000_E32_gen.pth'

**Comment by Janspiry** [comment]
Maybe you should @MazeOfEncryption

**Comment by owenlamont** [comment]
I just got the same error too with the Colab notebook...

**Comment by MazeOfEncryption** [comment]
I believe this occurs if the input image is not 64x64 images. For the time being, you can use an image editor to crop/resize your input image. As soon as I have time (will probably be a day or two), I'll add something to preprocess input images.

**Comment by MazeOfEncryption** [comment]
This seems to be an [issue with gdown](https://github.com/wkentaro/gdown/issues/43)

I'll try to figure out a workaround.

**Comment by MazeOfEncryption** [comment]
Trying to download the dataset manually gives this issue:
![image](https://user-images.githubusercontent.com/19843876/141647795-3effd680-7636-4c13-b5fb-1d6315cd5712.png)

**Comment by MazeOfEncryption** [comment]
@Janspiry Looks like the pre-trained model files are getting rate limited. Perhaps it would be better to upload the pre-trained model somewhere else? Either in a separate github repo, or on a different file hosting platform, etc.

**Comment by Janspiry** [comment]
Oh, I will update it soon. @MazeOfEncryption

**Comment by MazeOfEncryption** [comment]
> Oh, I will update it soon. @MazeOfEncryption 

Sounds good! If I were you, I would just make a new GitHub repo for it.

**Comment by KhaledAtya** [comment]
I am getting this error too on the Google Colab.

export CUDA_VISIBLE_DEVICES=0,1
21-11-13 14:56:23.767 - INFO:   name: distributed_high_sr_ffhq
  phase: val
  gpu_ids: [0, 1]
  path:[
    log: experiments/distributed_high_sr_ffhq_211113_145623/logs
    tb_logger: experiments/distributed_high_sr_ffhq_211113_145623/tb_logger
    results: experiments/distributed_high_sr_ffhq_211113_145623/results
    checkpoint: experiments/distributed_high_sr_ffhq_211113_145623/checkpoint
    resume_state: I830000_E32
    experiments_root: experiments/distributed_high_sr_ffhq_211113_145623
  ]
  datasets:[
    train:[
      name: FFHQ
      mode: HR
      dataroot: dataset/ffhq_64_512
      datatype: img
      l_resolution: 64
      r_resolution: 512
      batch_size: 2
      num_workers: 8
      use_shuffle: True
      data_len: -1
    ]
    val:[
      name: CelebaHQ
      mode: LRHR
      dataroot: dataset/celebahq_64_512
      datatype: img
      l_resolution: 64
      r_resolution: 512
      data_len: 50
    ]
  ]
  model:[
    which_model_G: sr3
    finetune_norm: False
    unet:[
      in_channel: 6
      out_channel: 3
      inner_channel: 64
      norm_groups: 16
      channel_multiplier: [1, 2, 4, 8, 16]
      attn_res: []
      res_blocks: 1
      dropout: 0
    ]
    beta_schedule:[
      train:[
        schedule: linear
        n_timestep: 2000
        linear_start: 1e-06
        linear_end: 0.01
      ]
      val:[
        schedule: linear
        n_timestep: 2000
        linear_start: 1e-06
        linear_end: 0.01
      ]
    ]
    diffusion:[
      image_size: 512
      channels: 3
      conditional: True
    ]
  ]
  train:[
    n_iter: 1000000
    val_freq: 10000.0
    save_checkpoint_freq: 10000.0
    print_freq: 50
    optimizer:[
      type: adam
      lr: 3e-06
    ]
    ema_scheduler:[
      step_start_ema: 5000
      update_ema_every: 1
      ema_decay: 0.9999
    ]
  ]
  distributed: True

21-11-13 14:56:23.774 - INFO: Dataset [LRHRDataset - CelebaHQ] is created.
21-11-13 14:56:23.774 - INFO: Initial Dataset Finished
21-11-13 14:56:40.215 - INFO: Loading pretrained model for G [I830000_E32] ...
Traceback (most recent call last):
  File "infer.py", line 46, in <module>
    diffusion = Model.create_model(opt)
  File "/content/Image-Super-Resolution-via-Iterative-Refinement/model/__init__.py", line 7, in create_model
    m = M(opt)
  File "/content/Image-Super-Resolution-via-Iterative-Refinement/model/model.py", line 42, in __init__
    self.load_network()
  File "/content/Image-Super-Resolution-via-Iterative-Refinement/model/model.py", line 158, in load_network
    gen_path), strict=(not self.opt['model']['finetune_norm']))
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
**FileNotFoundError: [Errno 2] No such file or directory: 'I830000_E32_gen.pth'**

**Comment by Janspiry** [comment]
> > Oh, I will update it soon. @MazeOfEncryption
> 
> Sounds good! If I were you, I would just make a new GitHub repo for it.
What can I do in  a new GitHub repo? I didn't try it in the before.

**Comment by sebastianffx** [comment]
I'm also getting the same error on colab

**Comment by enricorox** [comment]
For me it just works, you need to upload the models to the `/content/Image-Super-Resolution-via-Iterative-Refinement/` folder

**Comment by MazeOfEncryption** [comment]
> For me it just works, you need to upload the models to the `/content/Image-Super-Resolution-via-Iterative-Refinement/` folder

After this issue was posted, I added a section with instructions for manually uploading the model as a temporary workaround. 

In the future this will be fixed, but I'm glad to hear that the workaround works for now.

**Comment by MazeOfEncryption** [comment]
@Janspiry Actually, after looking into it a bit further, it looks like github has a limit of 100mb for files, and 1gb of storage + 1gb of bandwidth for large file storage, so I would not go that route. I'll see if I can find something else.

**Comment by Janspiry** [comment]
@MazeOfEncryption I see, thanks.

**Comment by owenlamont** [comment]
I'm not familiar with any public ML model repos but it seems like one of them would be ideal if you're looking for a place to make your model files available.

I noticed on Kaggle apparently some people use their public _datasets_ for pretrained model files - and they appear to have pretty generous  space limits. If you wanted to make a Kaggle Kernel version of the Colab notebook too, that might be a good option.

**Comment by Samox1** [comment]
I found a fairly simple solution but I can't test script because of error in "upscaling" part (at the end).

**The steps are as follows:**
1) Adding a shortcut of the "checkpoint" folder with .pth files to your google drive
2) Mounting the google drive in the colab script:
from google.colab import drive
drive.mount('/content/drive')
3) Copying the files using the shortcut:
!cp /content/drive/MyDrive/checkpoint/I830000_E32_gen.pth /content/Image-Super-Resolution-via-Iterative-Refinement/I830000_E32_gen.pth
!cp /content/drive/MyDrive/checkpoint/I830000_E32_opt.pth /content/Image-Super-Resolution-via-Iterative-Refinement/I830000_E32_opt.pth
4) (OPTIONAL) Checking the size of the copied files:
import os
print("From Google Drive, file I830000_E32_gen.pth should be about 592.7 MB ")
file_1 = os.stat('/content/Image-Super-Resolution-via-Iterative-Refinement/I830000_E32_gen.pth').st_size 
print(str(file_1) + " B = " + str(file_1/1024/1024) + " MB")
print("From Google Drive, file I830000_E32_opt.pth should be about 1.16 GB ")
file_2 = os.stat('/content/Image-Super-Resolution-via-Iterative-Refinement/I830000_E32_opt.pth').st_size 
print(str(file_2) + " B = " + str(file_2/1024/1024/1024) + " GB")

Please check if this works for you


Error in "Upscaling":
Traceback (most recent call last):
  File "infer.py", line 40, in <module>
    val_set = Data.create_dataset(dataset_opt, phase)
  File "/content/Image-Super-Resolution-via-Iterative-Refinement/data/__init__.py", line 34, in create_dataset
    need_LR=(mode == 'LRHR')
  File "/content/Image-Super-Resolution-via-Iterative-Refinement/data/LRHR_dataset.py", line 30, in __init__
    '{}/sr_{}_{}'.format(dataroot, l_resolution, r_resolution))
  File "/content/Image-Super-Resolution-via-Iterative-Refinement/data/util.py", line 16, in get_paths_from_images
    assert os.path.isdir(path), '{:s} is not a valid directory'.format(path)
AssertionError: dataset/celebahq_64_512/sr_64_512 is not a valid directory

**Comment by Janspiry** [comment]
> I'm not familiar with any public ML model repos but it seems like one of them would be ideal if you're looking for a place to make your model files available.
> 
> I noticed on Kaggle apparently some people use their public _datasets_ for pretrained model files - and they appear to have pretty generous space limits. If you wanted to make a Kaggle Kernel version of the Colab notebook too, that might be a good option.

Thanks a lot for your suggestion, It will be a nice choice.

**Comment by deama** [comment]
> I found a fairly simple solution but I can't test script because of error in "upscaling" part (at the end).
> 
> **The steps are as follows:**
> 
> 1. Adding a shortcut of the "checkpoint" folder with .pth files to your google drive
> 2. Mounting the google drive in the colab script:
>    from google.colab import drive
>    drive.mount('/content/drive')
> 3. Copying the files using the shortcut:
>    !cp /content/drive/MyDrive/checkpoint/I830000_E32_gen.pth /content/Image-Super-Resolution-via-Iterative-Refinement/I830000_E32_gen.pth
>    !cp /content/drive/MyDrive/checkpoint/I830000_E32_opt.pth /content/Image-Super-Resolution-via-Iterative-Refinement/I830000_E32_opt.pth
> 4. (OPTIONAL) Checking the size of the copied files:
>    import os
>    print("From Google Drive, file I830000_E32_gen.pth should be about 592.7 MB ")
>    file_1 = os.stat('/content/Image-Super-Resolution-via-Iterative-Refinement/I830000_E32_gen.pth').st_size
>    print(str(file_1) + " B = " + str(file_1/1024/1024) + " MB")
>    print("From Google Drive, file I830000_E32_opt.pth should be about 1.16 GB ")
>    file_2 = os.stat('/content/Image-Super-Resolution-via-Iterative-Refinement/I830000_E32_opt.pth').st_size
>    print(str(file_2) + " B = " + str(file_2/1024/1024/1024) + " GB")
> 
> Please check if this works for you
> 
> Error in "Upscaling": Traceback (most recent call last): File "infer.py", line 40, in val_set = Data.create_dataset(dataset_opt, phase) File "/content/Image-Super-Resolution-via-Iterative-Refinement/data/**init**.py", line 34, in create_dataset need_LR=(mode == 'LRHR') File "/content/Image-Super-Resolution-via-Iterative-Refinement/data/LRHR_dataset.py", line 30, in **init** '{}/sr_{}_{}'.format(dataroot, l_resolution, r_resolution)) File "/content/Image-Super-Resolution-via-Iterative-Refinement/data/util.py", line 16, in get_paths_from_images assert os.path.isdir(path), '{:s} is not a valid directory'.format(path) AssertionError: dataset/celebahq_64_512/sr_64_512 is not a valid directory

I'm getting the same error.

**Comment by MazeOfEncryption** [comment]
@Samox1 @deama This should be fixed now.

A recent pull request changed the default location to create the dataset folder, which is what caused this problem. 
![image](https://user-images.githubusercontent.com/19843876/142256748-83f5d632-993a-4679-979f-8b6752da174c.png)

**Comment by appelsiensam** [comment]
> 
> 
> Oh, I will update it soon. @MazeOfEncryption

The problem is that you made the links not able to download by everyone. change the option to "share with everyone"

**Comment by MazeOfEncryption** [comment]
> > 
> 
> > 
> 
> > Oh, I will update it soon. @MazeOfEncryption
> 
> 
> 
> The problem is that you made the links not able to download by everyone. change the option to "share with everyone"

No, even if it is set to share with everyone, this issue can occur. It's a known [issue with gdown](https://github.com/wkentaro/gdown/issues/43).

**Comment by iitjee** [comment]
@MazeOfEncryption Is the issue fixed? Apparently I still get the same error at the last cell

**Comment by MazeOfEncryption** [comment]
> 
> 
> @MazeOfEncryption Is the issue fixed? Apparently I still get the same error at the last cell

If the `gdown` command failed, did you try manually uploading the files?

**Comment by MazeOfEncryption** [comment]
> 
> 
> > I'm not familiar with any public ML model repos but it seems like one of them would be ideal if you're looking for a place to make your model files available.
> > I noticed on Kaggle apparently some people use their public _datasets_ for pretrained model files - and they appear to have pretty generous space limits. If you wanted to make a Kaggle Kernel version of the Colab notebook too, that might be a good option.
> 
> Thanks a lot for your suggestion, It will be a nice choice.

Yeah, this seems like a good option. It seems more reliable for this sort of thing compared to google drive. It looks like you can just make an account and upload the model files as a "dataset".

Kaggle api comes preinstalled on colab, so it will be quite easy to change the notebook to use it.

**Comment by bycloudai** [comment]
Don't know if you guys still looking for a colab solution, but I quickly modified the colab in this fork: https://github.com/bycloudai/ISRIR-colab

It'll mount onto your Google Drive like how @Samox1 suggested. Just need to create a folder in your base Google Drive called "ISRIR" and download & upload the checkpoints to that folder. Remember the mount GDrive step too. Hope this helps.
